import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Gamey Hub",
  description: "Generated by create next app",
};
//${inter.className}
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html>
      <body className="bg-[#151515] text-white">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
